### ISSUE TITLE
Should add check for invalid date

### ISSUE THREAD

**Issue by mirow** [bendrucker/postgres-date#1]
I think you should prevent parseDate from returning an invalid date object and return null instead, as this causes problems in Loopback. 
It's even possible to store a perfectly valid date into PostgreSQL, which still causes an "Invalid Date" object to be returned by parseDate, for example "0013-12-15".

A simple `isNaN(dateObj.getTime())` check would be enough.

**Comment by bendrucker** [comment]
Seems like invalid date checking is not the right solution here. `0013-12-15` can be represented as a JS date with no problems so if that's not working that's what we should fix. PR would be very welcome!

**Comment by mirow** [comment]
The function adds ' 00:00:00' to the date, and `new Date('0013-12-15 00:00:00')` yields an invalid JS date.

**Comment by bendrucker** [comment]
Sure, so let's fix that and figure out how to get a valid date.

**Comment by bendrucker** [comment]
`new Date('0013-12-15')` works fine, any idea why the time screws it up?

**Comment by mirow** [comment]
It seems to work correctly if I put the letter 'T' between the date and time (as specified in the ISO 8601 standard). So `new Date('0013-12-15T00:00:00')` is parsed correctly.

Just add the 'T' to your function:
```
if (!matches) {
  // Force YYYY-MM-DD dates to be parsed as local time
  return DATE.test(isoDate) ?
    new Date(isoDate + 'T00:00:00') :
    null
}
```

**Comment by bendrucker** [comment]
Yup, fixed!
