### ISSUE TITLE
Date rounding is causing issues, and is not consistent with postgres or native javascript date parsers

### ISSUE THREAD

**Issue by slickmb** [bendrucker/postgres-date#14]
I know that the recent change to round to the nearest millisecond (https://github.com/bendrucker/postgres-date/pull/10) was a response to https://github.com/brianc/node-postgres/issues/1200, but I propose that the original behavior of truncating the microseconds is actually the correct behavior, and that automatically rounding causes more issues than it solves.

The problem with rounding automatically is that it A) cannot be easily undone or worked around, and B) it does not match the behavior of JavaScript nor of postgres's date formatting functionality.

A few examples:

We have a date field that is stored in a `timestamptz(6)` column.  That date is also placed in a property of a JSONB field in another table used as a message queue.  When the row containing the original date and the row containing the JSONB version are loaded through `node-postgres`, we end up with different results:

```
const pg = require('pg');
const pool = new pg.Pool();

async function setup() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS example_1 (
            id SERIAL PRIMARY KEY,
            created_at TIMESTAMPTZ(6)
        );

        CREATE TABLE IF NOT EXISTS example_1_queue (
            id INT PRIMARY KEY,
            meta JSONB
        );
    `);
}

async function test() {
    const { rows: [ result1 ] } = await pool.query(`INSERT INTO example_1 (created_at) VALUES ('2020-01-01T01:01:01.123987Z') RETURNING *;`);
    const { rows: [ result2 ] } = await pool.query(`INSERT INTO example_1_queue (id, meta) SELECT e.id, row_to_json(e.*) FROM example_1 e WHERE id = $1 RETURNING *;`, [ result1.id ]);

    console.log('result1: %s (node-postgres)', result1.created_at.toISOString());
    console.log('result2: %s (JSONB -> new Date())', new Date(result2.meta.created_at).toISOString());
    // result1: 2020-01-01T01:01:01.124Z (node-postgres)
    // result2: 2020-01-01T01:01:01.123Z (JSONB -> new Date())
    // notice how the dates are different due to the difference between how node-postgres and javascript deal with dates.
}

async function run() {
    await setup();
    await test();
}

run();
```
You could argue that I  could round my dates when converting the JSONB ISO string back to a date (which is what I ended up having to do in order to upgrade to the latest node-postgres), but here's my counter-argument: why does your javascript date parser apply different behavior than my javascript interpreter's native date parser?  In my research, I have found no javascript interpreters that round to the nearest millisecond when parsing dates.

The other big problem with automatically rounding is that even postgres doesn't round when converting to ISO strings.  In our app, we have a few places where we have triggers that interpolate ISO dates into strings.  node-postgres's rounding also breaks this.  Here's an example:

```
const pg = require('pg');
const pool = new pg.Pool();

async function setup() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS example_2 (
            id SERIAL PRIMARY KEY,
            created_at TIMESTAMPTZ(6)
        );
    `);
}

async function test() {
    const { rows: [ result1 ] } = await pool.query(`INSERT INTO example_2 (created_at) VALUES ('2020-01-01T01:01:01.123987Z') RETURNING *;`);
    const { rows: [ result2 ] } = await pool.query(`SELECT to_char(e.created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') iso_date FROM example_2 e WHERE id = $1;`, [ result1.id ]);

    console.log('result1: %s (node-postgres)', result1.created_at.toISOString());
    console.log('result2: %s (postgres to_char())', result2.iso_date);
    // result1: 2020-01-01T01:01:01.124Z (node-postgres)
    // result2: 2020-01-01T01:01:01.123Z (postgres to_char())
    // notice how the dates are different due to the difference between how node-postgres and postgrest deal with microseconds.
}

async function run() {
    await setup();
    await test();
}

run();
```

My final argument is an edge case that has to do with aggregations.  It is common to use `date_trunc` to get sums, counts, and other aggregates by date in postgres.  The problem is that because node-postgres now rounds, it is possible for the row to be aggregated into one year, but for node-postgres to report an entirely different year.  Take this example:

```

const pg = require('pg');
const pool = new pg.Pool();

async function setup() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS example_3 (
            id SERIAL PRIMARY KEY,
            created_at TIMESTAMPTZ(6)
        );
    `);
}

async function test() {
    const { rows: [ result1 ] } = await pool.query(`INSERT INTO example_3 (created_at) VALUES ('2020-12-31T23:59:59.999999Z') RETURNING *;`);
    const { rows: [ result2 ] } = await pool.query(`SELECT date_trunc('YEAR', e.created_at) AS year FROM example_3 e WHERE id = $1;`, [ result1.id ]);

    console.log('result1: %s (node-postgres)', result1.created_at.getYear());
    console.log('result2: %s (postgres date_trunc())', result2.year.getYear());

    // result1: 120 (node-postgres)
    // result2: 119 (postgres date_trunc())
    // notice how the years are different due to the difference between how node-postgres and postgres deal with microseconds.
    // node-postgres rounded up to the next year. 
}

async function run() {
    await setup();
    await test();
}

run();
```

This is a bit of an edge case, but this CAN happen and is probably the biggest argument for reverting the millisecond rounding behavior.  Doing this at the year level is taking it to the extreme, but the same thing can happen at the month, day, hour, minute, and seconds level. 
 
If a record is created in December 2020, and someone asks what month was this record created, the answer should be December 2020.  But node-postgres's answer would be January 2021 in the above example.  This is why rounding dates is a bad idea, and why most date parsers available today don't do it (native javascript doesn't do it, `momentjs` doesn't do it unless you install an explicit plugin to change the behavior, postgres doesn't do it unless you explicitly re-cast your data types).

In the end, I believe the argument to round the dates was that rounding dates matches the behavior postgres exhibits when when casting to `timestamptz(3)`.  My counter argument there is that if I wanted the behavior of a `timestamptz(3)` field, I would have used a `timestamptz(3)` field, or I would have explicitly cast my data as a `timestamptz(3)` myself.  By rounding on the javascript side, you are making an assumption about how I'm intending to use my data, and forcing me into a behavior I did not want: a behavior that doesn't match the behavior of most javascript date parsers.  And worse, there's no way to undo the rounding once it's done on the javascript side.  The only way for me to work around this and restore the original behavior would be for me to go through each of my queries and truncate the dates to the milliseconds myself on the postgres side.  

I get that there are use cases where rounding makes some sense, but rounding by default to solve those cases is an example of the tail wagging the dog.  It is far easier to explicitly add rounding if you want it than it is to remove the rounding if you don't want it.

My proposal is to either remove the rounding altogether, or at the very least make it an optional behavior that can be turned on.

**Comment by bendrucker** [comment]
@salper Let me know what you think. I’m not into the idea of having an option. If you have a counter argument to the contention here that rounding is less correct/expected happy to hear.

**Comment by slickmb** [comment]
Added a pull request.  Made it optional in the spirit of compromise, but I also agree that making it optional adds complexity that doesn't really need to be there.  I can remove the optional bit from my pull if we agree that this is the correct course.

**Comment by bendrucker** [comment]
Great, appreciate the illustration of how the option would be implemented even if we elect not to use it.

**Comment by salper** [comment]
As said earlier, I also think we are talking about two different things here: format and value. I do want sorting tuples using a date type in Postgres to have the same result than sorting using javascript (when microsecond precision is involved). So I do need rounding. Even in Postgres, sorting tuples with or without truncating dates will have different results, as we lose data during truncation. The only legit problem here IMHO is the Postgres JSON native serialization. I'm pretty surprised  because converting to timestamp do involve rounding. It maybe a Postgres consistency issue. Does Postgres team see JSON serialization as a formatting problem?

**Comment by salper** [comment]
But I do understand the issue working with date parts when working with rounding, and that's probably why other libraries do not round. That's tricky...

**Comment by slickmb** [comment]
To answer your first point: when postgres serializes into json, it includes the full precision in ISO format.  It's not until the data hit's javascript-land that the microseconds get truncated by javascript's native date parser.

```
select row_to_json(e.*) FROM expel_1 WHERE id = 8;
--
-- {
--  id: 8,
--  meta: { id: 8, created_at: '2020-01-01T01:01:01.123987+00:00' }
-- }
```

**Comment by slickmb** [comment]
I have another idea for how we could solve this and support both use cases...  Supply two parsers.  The default parser would not round (and thus keep pg's original behavior), but the second parser would round.   I'll update my pull request to illustrate what I mean...

**Comment by slickmb** [comment]
Updated my pull with a separate commit.  I'll squash them before merging if this is the route we choose.

**Comment by slickmb** [comment]
We could even add a convenience function that updates the pg parse types for you... something like:

```
   /**
 * Usage:
 *   const pg = require('pg');
 *   const postgresDate = require('postgres-date');
 *   postgresDate.applyRoundedParsingToNodePostgres(pg);
 *
 * @param pg
 */
module.exports.applyRoundedParsingToNodePostgres = function applyRoundingToPg (pg) {
  pg.types.setTypeParser(1082, module.exports.parseDateRounded); // date
  pg.types.setTypeParser(1083, module.exports.parseDateRounded); // time
  pg.types.setTypeParser(1114, module.exports.parseDateRounded); // timestamp
  pg.types.setTypeParser(1184, module.exports.parseDateRounded); // timestamptz
  pg.types.setTypeParser(1266, module.exports.parseDateRounded); // timetz
}
```

**Comment by slickmb** [comment]
Updated my pull with the above convenience function.

**Comment by slickmb** [comment]
Updated the pull to better match how pg-types uses postgres-date.

Perhaps pg-types would actually be a more appropriate place for this convenience function...

**Comment by slickmb** [comment]
yeah.  just realized that it won't work here.  Will open a pull against pg-types to add this convenience function if this ends up being the route we go.  removing the convenience function from my pull for now.

**Comment by slickmb** [comment]
Still my point is that sorting tuples is a valid use-case for rounding, but it is just one use case.  I don't think it's correct to change the behavior of your parser to deviate from the expected behavior of standard javascript parsers, and in the process break multiple other user-cases, just to support a single use case .  That one use case can be solved with a custom parser.

**Comment by salper** [comment]
I do agree on your point. It's not really a question of single use case, there are probably other ones. But the fact that javascript land does not round dates is enough for me to dismiss the initial commit. How about it @bendrucker?

**Comment by slickmb** [comment]
I've squashed and rebased my pull.  I think that offering the optional second parser as a convenience is a far better approach than my original static property suggestion.  @salper, would having that second parser actually help address your use-case?  Or would it be better to just revert the original change and have done with it?

**Comment by slickmb** [comment]
Updated my pull with documentation updates.

**Comment by bendrucker** [comment]
Agreed on reverting the default behavior. @salper is `parseDateRounded` something you'd use?

**Comment by salper** [comment]
I can live with the information loss, as long as it is standard javascript. Thanks for asking.

**Comment by dko-slapdash** [comment]
JFYI for future readers: `ts::timestamptz(3)` does rounding, and `date_trunc('milliseconds', ts)` does truncation (the truncation works the same way as postgres-date module used by node-postgres).

```
# select
  '2023-08-12 19:35:53.973605-07'::timestamptz, 
  '2023-08-12 19:35:53.973605-07'::timestamptz::timestamptz(3),
  date_trunc('milliseconds', '2023-08-12 19:35:53.973605-07'::timestamptz) \gx
-[ RECORD 1 ]------------------------------
timestamptz | 2023-08-12 19:35:53.973605-07
timestamptz | 2023-08-12 19:35:53.974-07
date_trunc  | 2023-08-12 19:35:53.973-07
```
