### ISSUE TITLE
Doesn't support special values

### ISSUE THREAD

**Issue by vitaly-t** [bendrucker/postgres-date#3]
Date types in PostgreSQL can store special values: `+Infinity`, `-Infinity`.

This library feeds those back as `null`.

**Comment by bendrucker** [comment]
Didn't know that! FYI, it's `infinity` and `-infinity`.

**Comment by vitaly-t** [comment]
>it's infinity and -infinity.

PostgreSQL supports all of them, from `+Infinity` / `-Infinity` to just `infinity` and `-infinity`, and it is not even case sensitive ;)

Thank you for the change!

**Comment by bendrucker** [comment]
On insertion it might but it looked like the output will always be the [two documented values](http://www.postgresql.org/docs/9.5/static/datatype-datetime.html#AEN6209) I mentioned.

![screenshot](http://d.pr/i/93Bn+)

The parser assumes the two documented values are the only possibilities. If it is possible to *return* the cases/punctuation variations you mentioned the parser would need to be updated.

**Comment by vitaly-t** [comment]
Yeah, that's what I meant, just didn't quite say it :+1:
