### ISSUE TITLE
Save original input (unmodified) timestamp string in a custom Date prop

### ISSUE THREAD

**Issue by dko-slapdash** [bendrucker/postgres-date#37]
Hi. 

Since the parser recognizes not more than 3 precision digits of the timestamp seconds (whilst PG returns up to 6 of them), why not just assign an additional custom prop to the returned JS Date object, the same way as it’s proposed here: https://github.com/typeorm/typeorm/issues/4964#issuecomment-1657300701 ?

This would’ve been backward compatible, and we would’ve still not lost the data (PG keeps microseconds precision by default). So the users of e.g. node-postgres would’ve been able to extract the precise (untruncated) PG timestamp from JS Date object by default.

**Comment by bendrucker** [comment]
Mutating built-in objects doesn't seem like a great idea especially when it comes to typing. It's a clever hack but not something that seems justified to add here.
