### ISSUE TITLE
Fails to parse an ISO date with "T" inside

### ISSUE THREAD

**Issue by AzariasB** [bendrucker/postgres-date#38]
I don't know if it's in the scope of this library:
when parsing a date in the ISO format `2011-01-23T22:15:51.000Z` with a `T` instead of a space to separate the date from the time, postgres-date returns null.

Changing [this line](https://github.com/bendrucker/postgres-date/blob/b7fb4cc3c4600330e5c398617ff7b99f3984b95d/index.js#L211) to accept a T as well should fix the problem.

Let me know if I can create a PR with the fix!

**Comment by bendrucker** [comment]
Does Postgres actually produce that?

https://github.com/bendrucker/postgres-date?tab=readme-ov-file#postgres-date-

**Comment by AzariasB** [comment]
Not directly from a date column no.
What happens in my case is that I have a json string that contains a date with this format and it is not correctly parsed when using  postgres-date.
As I said, if you think this is out of scope for the library, I understand.

**Comment by bendrucker** [comment]
Yes, out of scope, this is for parsing Postgres dates. JSON you can just parse with `Date.parse`.
